import { StyleSheet } from "react-native";

let styles = StyleSheet.create({
  logoContainer: {
    alignItems: "center",
    marginTop: 50,
    marginBottom: 20,
  },
  logo: {
    height: 200,
    width: 200,
  },
  inputMail: {
    backgroundColor: "#FFF6E8",
    borderRadius: 100,
    marginHorizontal: 30,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginVertical: 10,
    paddingLeft: 18,
    zIndex: 0,
    paddingRight: 18,
    letterSpacing: 2,
  },
  inputPass: {
    backgroundColor: "#FFF6E8",
    borderRadius: 100,
    marginHorizontal: 30,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginVertical: 10,
    paddingLeft: 18,
    zIndex: 0,
    paddingRight: 50,
    letterSpacing: 2,
  },
  containerEye: {
    position: "absolute",
    flexDirection: "row-reverse",
    alignItems: "center",
    elevation: 6,
    zIndex: 6,
    left: "82%",
    top: "31%",
  },
  eye: {
    height: 25,
    width: 25,
    zIndex: 6,
  },
  button: {
    backgroundColor: "#FFC680",
    borderRadius: 100,
    marginHorizontal: 30,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginVertical: 10,
  },
  buttonText: {
    color: "#DD8643",
    textAlign: "center",
    shadowColor: "#171717",
    fontSize: 16,
    letterSpacing: 2,
  },
  text: {
    fontSize: 20,
    marginBottom: 10,
    letterSpacing: 6,
  },
  forgotPass: {
    opacity: 0.6,
    marginVertical: 10,
    letterSpacing: 2,
  },
  containerRegisterNow: {
    position: "absolute",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
    width: "100%",
    height: "100%",
    bottom: 10,
    // flexDirection: "row",
    // justifyContent: "center",
    // alignItems: "flex-end",
    // marginTop: 20,
  },
  notAccount: {
    opacity: 0.6,
    letterSpacing: 2,
  },
  registerNow: {
    color: "#DD8643",
    opacity: 0.6,
    letterSpacing: 2,
  },
});

export default styles;
